os: Visual Studio 2015

platform: x64

configuration: Release

environment:
    
    PYTHON_ROOT: C:\Python36-x64
    PYTHON_VERSION: 3.6
    
    MINICONDA: C:\Miniconda36-x64
    SWIG_ROOT:
    
 
install:
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  
  # USING VCPKG FOR INSTALLING STANDARD LIBRARIES
  - cmd: >-
        cd C:\
        
        IF NOT EXIST c:\vcpkg\    
        (git clone https://github.com/Microsoft/vcpkg.git)        
        (git checkout 517b3fabbbb713d7483a62f71446623d80d04e97)
        ELSE ( echo VCPKG is cached )
        
        cd vcpkg        
        
        powershell -exec bypass scripts\bootstrap.ps1
        
        .\vcpkg install sqlite3:x64-windows eigen3:x64-windows boost:x64-windows gsl:x64-windows
  
        
  # To install SWIG in home directory using choco
  - ps: choco install -y swig > $null
  
  # Using MINICONDA pre installed to setup  pyqt and numpy
  - cmd: call C:\Miniconda36-x64\Scripts\activate.bat
  
  #- "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda install --yes --quiet pyqt=5.6.0
  # Using MINICONDA pre installed to setup  NumPy
  - conda install --yes --quiet numpy=1.12.1
  #- cmd: which pkg-config
  - ps: choco install -y sqlite --version 3.19.2
  
  

before_build:
  - cmd: cd C:/projects/cmakevisualstudio
  - cmd: md build && cd build
  #- cmd: cmake -G "Visual Studio 14 2015 Win64" ..
  
  #- ps: ls "C:/Miniconda36-x64/pkgs/pyqt-5.6.0-py36_2/Library/bin"
  #- ps: ls "C:/Program Files/gsl"
  - ps: ls "C:/projects/cmakevisualstudio"
   
  #- cmd: cmake -G "Visual Studio 14 2015 Win64" -DEIGEN3_INCLUDE_DIR=C:\projects\eigen-eigen-67e894c6cd8f\ ..
  - cmd: cmake -G "Visual Studio 14 2015 Win64" .. -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake"

build:
  project: build\hello.vcxproj
  parallel: true
  verbosity: minimal

artifacts:
  - path: build\Release\hello.exe
    name: installer
    
cache: 
- C:\vcpkg\installed\x64-windows
- C:\vcpkg\packages
- C:\Miniconda36-x64
- C:\ProgramData\chocolatey\bin
- C:\ProgramData\chocolatey\lib  

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token: $(GH_TOKEN)
    artifact:  installer
    prerelease: true
    force_update: true
    on:
      appveyor_repo_tag: true  
  
  

 
