os: Visual Studio 2015

platform: x64

configuration: Release

environment:
    
    PYTHON_ROOT: C:\Python36-x64
    PYTHON_VERSION: 3.6
    
    MINICONDA: C:\Miniconda36-x64    
 
install:
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

  - ps: Start-FileDownload 'https://github.com/seweber/pairinteraction-build-dependencies/releases/download/v64/vcpkg-export.zip'
  - cmd: 7z x -y vcpkg-export.zip > nul
  - cmd: move vcpkg-export-* vcpkg-export

  - ps: choco install -y swig --version 3.0.9
  - ps: choco install -y sqlite --version 3.19.2

  - cmd: call C:\Miniconda36-x64\Scripts\activate.bat
  - cmd: conda install -y -q pyqt=5.6.0 numpy=1.12.1

before_build:
  - cmd: md build && cd build
  - cmd: cmake -G "Visual Studio 14 2015 Win64" .. -DCMAKE_TOOLCHAIN_FILE=vcpkg-export\scripts\buildsystems\vcpkg.cmake"

build:
  project: build\hello.vcxproj
  parallel: true
  verbosity: minimal

artifacts:
  - path: build\Release\hello.exe
    name: installer

cache:
- C:\ProgramData\chocolatey\bin
- C:\ProgramData\chocolatey\lib

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token: $(GH_TOKEN)
    artifact:  installer
    prerelease: true
    force_update: true
    on:
      appveyor_repo_tag: true  
  
  

 
